apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml

generatorOptions:
  annotations:
    argocd.argoproj.io/sync-options: Replace=true

configMapGenerator:
  - name: news-feed-script
    namespace: feedreader
    files:
      - news_feed_cyberpunk.py
      - api_server.py
  - name: nginx-config
    namespace: feedreader
    files:
      - default.conf=nginx-default.conf
      - loading.html=nginx-loading.html
